from __future__ import annotations

import time
from collections.abc import Callable

from ptq.domain.models import PRResult, PtqError
from ptq.infrastructure.backends import backend_for_job
from ptq.infrastructure.job_repository import JobRepository
from ptq.ssh import Backend

_HTTPS_TO_SSH = {
    "https://github.com/": "git@github.com:",
}

_PR_STATE_TTL_SECONDS = 45.0
_pr_state_cache: dict[str, tuple[float, str]] = {}


def _read_file(backend: Backend, path: str) -> str:
    result = backend.run(f"cat {path}", check=False)
    return result.stdout.strip() if result.returncode == 0 else ""


def _normalize_pr_state(raw_state: str, merged_at: str) -> str:
    match raw_state.upper():
        case "OPEN":
            return "open"
        case "MERGED":
            return "merged"
        case "CLOSED":
            return "merged" if merged_at else "closed"
        case _:
            return "unknown"


def get_pr_state(
    backend: Backend,
    pr_url: str,
    *,
    force_refresh: bool = False,
    ttl_seconds: float = _PR_STATE_TTL_SECONDS,
) -> str:
    if not pr_url:
        return "unknown"

    now = time.monotonic()
    cached = _pr_state_cache.get(pr_url)
    if not force_refresh and cached and now - cached[0] < ttl_seconds:
        return cached[1]

    result = backend.run(
        f"gh pr view '{pr_url}' --json state,mergedAt --jq '[.state, (.mergedAt // \"\")] | @tsv'",
        check=False,
    )
    if result.returncode != 0:
        state = "unknown"
    else:
        raw_state, _, merged_at = result.stdout.strip().partition("\t")
        state = _normalize_pr_state(raw_state.strip(), merged_at.strip())
    _pr_state_cache[pr_url] = (now, state)
    return state


def _build_pr_body(
    report: str,
    worklog: str,
    repro: str,
    issue_number: int | None,
    human_note: str,
) -> str:
    parts: list[str] = [
        "## Human Note",
        human_note,
    ]
    if report:
        parts.append(f"\n## Agent Report\n{report}")
    if issue_number is not None:
        parts.append(f"\n\nFixes #{issue_number}")
    if repro:
        parts.append(
            f"\n\n<details>\n<summary>Repro Script</summary>\n\n```python\n{repro}\n```\n\n</details>"
        )
    if worklog:
        parts.append(
            f"\n\n<details>\n<summary>Agent Worklog</summary>\n\n{worklog}\n\n</details>"
        )
    parts.append(
        "\n---\n*This PR was generated by [ptq](https://github.com/drisspg/pt_job_queue) "
        "with human review.*"
    )
    return "\n".join(parts)


def _ensure_ssh_remote(
    backend: Backend, worktree: str, _log: Callable[[str], None]
) -> None:
    result = backend.run(f"cd {worktree} && git remote get-url origin", check=False)
    url = result.stdout.strip()
    for https_prefix, ssh_prefix in _HTTPS_TO_SSH.items():
        if url.startswith(https_prefix):
            ssh_url = url.replace(https_prefix, ssh_prefix)
            if not ssh_url.endswith(".git"):
                ssh_url += ".git"
            _log(f"Switching origin to SSH: {ssh_url}")
            backend.run(f"cd {worktree} && git remote set-url origin '{ssh_url}'")
            return


def create_pr(
    repo: JobRepository,
    job_id: str,
    *,
    human_note: str,
    title: str | None = None,
    draft: bool = False,
    log: Callable[[str], None] | None = None,
) -> PRResult:
    if not human_note.strip():
        raise PtqError(
            "A human note is required. Describe what this PR does, "
            "why you believe it's correct, and how the reviewer should approach it."
        )

    _log = log or (lambda _: None)
    job = repo.get(job_id)
    backend = backend_for_job(job)
    job_dir = f"{backend.workspace}/jobs/{job_id}"
    worktree = f"{job_dir}/pytorch"
    existing_open_pr_url = ""

    if job.pr_url:
        pr_state = get_pr_state(backend, job.pr_url, force_refresh=True)
        match pr_state:
            case "open":
                existing_open_pr_url = job.pr_url
                _log(f"Existing PR is open: {existing_open_pr_url}")
            case "closed" | "merged":
                _log(f"Stored PR is {pr_state}. Creating a new PR from current branch.")
            case _:
                _log("Stored PR state is unknown. Proceeding with create-or-find flow.")

    branch = f"ptq/{job.issue}" if job.issue is not None else f"ptq/{job_id}"
    pr_title = title or (
        f"Fix #{job.issue}" if job.issue is not None else f"Fix from {job_id}"
    )

    _log(f"Branch: {branch}")
    _log(f"Title: {pr_title}")

    report = _read_file(backend, f"{job_dir}/report.md")
    worklog = _read_file(backend, f"{job_dir}/worklog.md")
    repro = _read_file(backend, f"{job_dir}/repro.py")
    body = _build_pr_body(report, worklog, repro, job.issue, human_note)
    _log(
        f"PR body: report.md {'found' if report else 'missing'}, "
        f"worklog.md {'found' if worklog else 'missing'}, "
        f"repro.py {'found' if repro else 'missing'}"
    )

    commit_msg = pr_title.replace("'", "'\\''")
    _log(f"Checking out branch {branch}...")
    backend.run(f"cd {worktree} && git checkout -B '{branch}'")
    _log("Staging changes...")
    backend.run(f"cd {worktree} && git add -A")
    backend.run(
        f"cd {worktree} && git reset HEAD -- .claude/ .cursorrules AGENTS.md",
        check=False,
    )
    has_staged_changes = (
        backend.run(
            f"cd {worktree} && git diff --cached --quiet", check=False
        ).returncode
        != 0
    )
    if has_staged_changes:
        _log("Creating commit...")
        commit_result = backend.run(
            f"cd {worktree} && git commit -m '{commit_msg}'",
            check=False,
        )
        if commit_result.returncode != 0:
            stderr = commit_result.stderr.strip() if commit_result.stderr else ""
            stdout = commit_result.stdout.strip() if commit_result.stdout else ""
            raise PtqError(f"git commit failed: {stderr or stdout or 'unknown error'}")
    else:
        _log("No staged changes to commit.")

    _ensure_ssh_remote(backend, worktree, _log)
    _log("Pushing branch...")
    push_result = backend.run(
        f"cd {worktree} && git push -u origin '{branch}'",
        check=False,
    )
    if push_result.returncode != 0:
        stderr = push_result.stderr.strip() if push_result.stderr else ""
        stdout = push_result.stdout.strip() if push_result.stdout else ""
        raise PtqError(f"git push failed: {stderr or stdout or 'unknown error'}")
    body_escaped = body.replace("'", "'\\''")
    url = ""
    if existing_open_pr_url:
        _log("Updating existing PR...")
        edit_result = backend.run(
            f"cd {worktree} && "
            f"gh pr edit '{existing_open_pr_url}' "
            f"--title '{commit_msg}' "
            f"--body '{body_escaped}'",
            check=False,
        )
        if edit_result.returncode == 0:
            url = existing_open_pr_url
        else:
            _log("Could not update existing PR, falling back to create-or-find flow.")

    result = None
    if not url:
        _log("Creating PR...")
        result = backend.run(
            f"cd {worktree} && "
            f"gh pr create "
            f"--title '{commit_msg}' "
            f"--body '{body_escaped}' "
            f"--head '{branch}'"
            f"{' --draft' if draft else ''}",
            check=False,
        )
        for line in result.stdout.strip().splitlines():
            if line.startswith("http"):
                url = line.strip()
                break

    if not url and result and result.returncode != 0:
        stderr = result.stderr.strip() if result.stderr else ""
        if "already exists" in stderr:
            url = backend.run(
                f"cd {worktree} && gh pr list --head '{branch}' --state open --json url --jq '.[0].url'",
                check=False,
            ).stdout.strip()
            if url:
                _log("Updating existing PR body...")
                backend.run(
                    f"cd {worktree} && gh pr edit '{branch}' --body '{body_escaped}'",
                    check=False,
                )
        if not url:
            raise PtqError(f"gh pr create failed: {stderr or result.stdout}")

    if url:
        job.pr_url = url
        job.human_note = human_note
        repo.save(job)

    return PRResult(url=url, branch=branch)
